# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cli_ax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='det_ax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=128)),
                ('org', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('timep', models.CharField(max_length=128)),
                ('geol', models.CharField(max_length=128)),
                ('month', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
            ],
        ),
    ]
